### ISSUE TITLE
Ewald for NaCl

### ISSUE THREAD

**Issue by bikramjitkarmakar** [NaveenKaliannan/EwaldSummation#1]
I modified the input file to suit for NaCl but the result is different. Do help

**Comment by NaveenKaliannan** [comment]
Hi,

Sorry for the late reply. I have calculated for NaCl using the below input file. The result will be 0.871923.  Multiply it with 2, you will get (0.871923 * 2 =) 1.743846, which is the Madelung constant of NaCl. The program is not written in a way to normalize the result to Madelung constant. 

 In case if you have any problem or error, just let me know.

Kind Regards,
Naveen
Paderborn

## Input file:
1 1 1
2.814
8
1
1 -1
5.64 5.64 5.64
0   0   0    1
0.5 0.5 0    1
0.5 0   0.5  1
0   0.5 0.5  1
0.5 0   0   -1
0   0.5 0   -1
0   0   0.5 -1
0.5 0.5 0.5 -1

**Comment by NaveenKaliannan** [comment]
Hi,

Sorry for the late reply. I have calculated for NaCl using the below input file. The result will be 0.871923.  Multiply it with 2, you will get (0.871923 * 2 =) 1.743846, which is the Madelung constant of NaCl. The program is not written in a way to normalize the result to Madelung constant. 

 In case if you have any problem or error, just let me know.

Kind Regards,
Naveen
Paderborn

## Input file:
1 1 1
2.814
8
1
1 -1
5.64 5.64 5.64
0   0   0    1
0.5 0.5 0    1
0.5 0   0.5  1
0   0.5 0.5  1
0.5 0   0   -1
0   0.5 0   -1
0   0   0.5 -1
0.5 0.5 0.5 -1
